apiVersion: v2
name: frontend-spa
description: A Helm chart for deploying a frontend Single Page Application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - frontend
  - spa
maintainers:
  - name: Your Name
    email: your.email@example.com