# Default values for frontend-spa chart
replicaCount: 1

image:
  repository: nginx  # Placeholder for frontend SPA image
  pullPolicy: IfNotPresent
  tag: ""  # Defaults to appVersion in Chart.yaml if not specified

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  enabled: true  # Can be disabled if needed
  type: ClusterIP
  port: 80

ingress:
  enabled: false  # Disabled by default
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Additional environment variables to pass to the container
extraEnvVars: []
  # - name: ENV_VAR_NAME
  #   value: "value"
  # - name: SECRET_ENV_VAR
  #   valueFrom:
  #     secretKeyRef:
  #       name: secret-name
  #       key: secret-key

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

nodeSelector: {}
tolerations: []
affinity: {}